"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import type { PublicAuction, PublicConfig } from "@/lib/api-types";
import { api, dateTime, zec } from "@/lib/ui-utils";
import { Arrow, AuctionArt, ErrorNotice, Loading, Phase, SealMark } from "@/components/ui";
type FloorData={auctions:PublicAuction[];pending?:{id:string;title:string;transactionHash:string}[];config:PublicConfig};
export default function Home() {
  const [data,setData]=useState<FloorData|null>(null);const [error,setError]=useState(""); const [filter,setFilter]=useState("all");
  useEffect(()=>{api<FloorData>("/api/auctions").then(setData).catch(e=>setError(e.message));},[]);
  const auctions=data?.auctions.filter(a=>filter==="all" || (filter==="open"?a.phase==="open":a.phase.startsWith("verified")))??[];
  return <main id="main"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> A FAIRER WAY TO FIND THE PRICE</div><h1>Bid in private.<br/>Win with <em>proof.</em></h1><p className="hero-description">Your bid stays yours. The winning result is verifiable.<br className="desktop-break"/> An auction house built for a more private internet.</p><div className="hero-actions"><a href="#auctions" className="button button-primary">Explore auctions <Arrow/></a><a href="#how-it-works" className="text-link">See how it works <Arrow diagonal/></a></div><div className="hero-footnote"><SealMark size={18}/><span>Shielded Zcash payments<span className="divider-dot">·</span>Zero-knowledge winner proofs</span></div></div><AuctionArt large/></section>
    <section className="principles" aria-label="Auction principles"><div><span className="mono muted">01 / CONFIDENTIAL</span><strong>Sealed until the deadline.</strong></div><div><span className="mono muted">02 / VERIFIABLE</span><strong>The highest valid bid wins.</strong></div><div><span className="mono muted">03 / SHIELDED</span><strong>Settle directly in ZEC.</strong></div><span className="testnet-label">EXPERIMENTAL<br/><b>TESTNET EDITION</b></span></section>
    <section id="auctions" className="auction-section"><div className="section-heading"><div><div className="eyebrow muted">THE AUCTION FLOOR</div><h2>Find your next <em>discovery.</em></h2></div><div className="network-status"><span className={`dot ${data?.config.ready?"":"quiet"}`}/>{data?.config.ready?(data.config.chainId===31337?"Local development registry":"Base Sepolia registry configured"):"Network connection pending"}</div></div><div className="filter-row"><div className="tabs" role="group" aria-label="Filter auctions">{[["all","All auctions"],["open","Open for bids"],["verified","Verified results"]].map(([key,label])=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{label}{key==="all"&&data?<span>{data.auctions.length}</span>:null}</button>)}</div><span className="mono muted">ZEC / {data?.config.chainId===31337?"LOCAL EVM EVIDENCE":"BASE SEPOLIA EVIDENCE"}</span></div>
    {error?<ErrorNotice message={error}/>:!data?<Loading label="Connecting to the auction registry…"/>:auctions.length?<div className="auction-grid">{auctions.map(a=><Link key={a.id} href={`/auctions/${a.id}`} className="auction-card"><AuctionArt/><div className="card-content"><div className="card-meta"><span className="mono muted">{a.category}</span><Phase phase={a.phase}/></div><h3>{a.title}</h3><p>{a.description}</p><div className="card-bottom"><div><span className="mono muted">{a.result?.sale?"WINNING PRICE":"RESERVE PRICE"}</span><strong>{zec(a.result?.sale?a.result.price:a.reserve)} <small>ZEC</small></strong></div><div className="card-time"><span className="mono muted">{a.bidCount}/{a.capacity} BIDS</span><span>{dateTime(a.closesAt)}</span></div></div></div></Link>)}</div>:<div className="empty-floor"><div className="empty-emblem"><SealMark size={42}/></div><div><span className="eyebrow muted">ROOM FOR SOMETHING WORTH BIDDING ON</span><h3>{filter==="all"?"The floor is yours.":"Nothing here just yet."}</h3><p>{filter!=="all"?"Try another filter to explore the auction floor.":data.config.ready?"No auctions have been published yet. Open the first one with rules everyone can verify.":"The first auction is on its way. The registry needs to be connected before bidding can begin."}</p></div><Link href={filter==="all"?"/create":"/#auctions"} onClick={()=>{if(filter!=="all")setFilter("all");}} className="button button-outline">{filter==="all"?"Create the first auction":"View all auctions"}<Arrow/></Link></div>}
    {data?.pending?.length?<div className="pending-auctions">{data.pending.map(a=><Link key={a.id} href={`/auctions/${a.id}`} className="pending-auction"><div><span className="mono muted">AWAITING REGISTRY FINALITY</span><h3>{a.title}</h3></div><Phase phase="pending"/><Arrow/></Link>)}</div>:null}
    <div className="floor-summary"><span>{data?.auctions.length??"—"} auctions listed</span><span>{data?.auctions.reduce((n,a)=>n+a.bidCount,0)??"—"} registered bids</span><span>No public bid amounts before closing</span></div></section>
    <section id="how-it-works" className="how-section"><div className="how-intro"><div className="eyebrow">PRIVACY, WITH RECEIPTS</div><h2>A closed bid.<br/>An <em>open standard.</em></h2><p>Trust the evidence. Every registered bid belongs in the result, and the proof must account for all of them.</p><Link href="/verify" className="text-link">Explore verification <Arrow diagonal/></Link></div><div className="steps">{[{n:"01",title:"Seal your offer",text:"Create a local identity and encrypt your bid in your browser. A time lock keeps honest submissions sealed until closing."},{n:"02",title:"Verify the outcome",text:"A zero-knowledge proof checks the highest valid bid against the complete registered set. Losing amounts stay off the public page."},{n:"03",title:"Pay without broadcasting it",text:"The winner claims a private invoice and pays the seller directly with shielded Zcash testnet funds."}].map(s=><div className="step" key={s.n}><span>{s.n}</span><div><h3>{s.title}</h3><p>{s.text}</p></div></div>)}</div></section>
    <div className="trust-note"><span className="mono">KNOW THE BOUNDARIES</span><p>The evaluator sees bids after opening. Participation metadata is public on Base. This prototype does not enforce payment or delivery, prevent shill bids, or hold funds in escrow.</p></div>
  </main>;
}
