import Link from "next/link";
import type { AuctionPhase } from "@/lib/api-types";
export function Arrow({diagonal=false}:{diagonal?:boolean}) { return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal?"M6 18 18 6M6 6h12v12":"M4 12h16m-6-6 6 6-6 6"} stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
export function SealMark({size=28}:{size?:number}) { return <svg width={size} height={size} viewBox="0 0 36 36" fill="none" aria-hidden="true"><path d="M18 2 32 10v16l-14 8L4 26V10L18 2Z" stroke="currentColor" strokeWidth="2"/><path d="m11 12 7-4 7 4-14 12 7 4 7-4M11 12v5l14 2v5" stroke="currentColor" strokeWidth="2"/></svg>; }
export function Nav() {return <header className="nav"><Link href="/" className="wordmark" aria-label="Sealed home"><SealMark/><span>SEALED<span className="brand-sub">PRIVATE AUCTIONS</span></span></Link><nav aria-label="Main navigation"><Link href="/#auctions">Auctions</Link><Link href="/#how-it-works">How it works</Link><Link href="/verify">Verify a result</Link></nav><Link href="/create" className="button button-small button-outline">Create auction <span className="plus">+</span></Link></header>;}
export function Footer(){return <footer className="footer"><Link href="/" className="wordmark"><SealMark size={22}/><span>SEALED</span></Link><p>Private bids. Verifiable outcomes. Shielded settlement.</p><span className="mono muted">BUILT FOR ZCASH · TESTNET ONLY</span></footer>;}
const names: Record<AuctionPhase,string>={open:"Accepting bids",opening:"Waiting to open",proving:"Generating proof",blocked:"Opening blocked","verified-sale":"Verified sale","verified-no-sale":"Verified no-sale",expired:"Expired",pending:"Pending registration"};
export function Phase({phase}:{phase:AuctionPhase}) {return <span className={`phase ${phase}`}><i/>{names[phase]}</span>;}
export function ErrorNotice({message}:{message:string}) {return <div className="notice error" role="alert">{message}</div>;}
export function Loading({label="Loading auction evidence…"}:{label?:string}) {return <div className="loading" role="status"><span className="spinner"/>{label}</div>;}
export function AuctionArt({large=false}:{large?:boolean}) {return <div className={`auction-art ${large?"large":""}`} aria-hidden="true"><div className="art-grid"/><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-box"><div className="art-fold"/><div className="art-seal"><SealMark size={large?52:32}/></div></div><span className="art-coordinate">SEALED / ZK-01</span><span className="art-caption">ONLY THE PROOF GETS OUT.</span></div>;}
