"use client";
import { Suspense, useState, type FormEvent } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import type { PublicAuction } from "@/lib/api-types";
import { api, downloadJson, short, zec } from "@/lib/ui-utils";
import { Arrow, ErrorNotice, Phase, SealMark } from "@/components/ui";
function VerifyContent(){const search=useSearchParams();const [id,setId]=useState(search.get("auction")??""),[auction,setAuction]=useState<PublicAuction|null>(null),[proof,setProof]=useState<unknown>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
async function inspect(event:FormEvent){event.preventDefault();setBusy(true);setError("");setProof(null);setAuction(null);try{if(!/^[1-9][0-9]*$/.test(id))throw new Error("Enter a numeric auction ID.");const value=await api<{auction:PublicAuction}>(`/api/auctions/${id}`);setAuction(value.auction);if(value.auction.proofAvailable)setProof(await api<unknown>(`/api/auctions/${id}/proof`));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
return <main id="main" className="page-content verify-page"><div className="breadcrumb"><Link href="/">The auction floor</Link><span>/</span><span>INDEPENDENT VERIFICATION</span></div><div className="verify-heading"><div><span className="eyebrow">DON’T TAKE OUR WORD FOR IT</span><h1>The result has<br/><em>to prove itself.</em></h1><p>Check the evidence behind a winning bid. The proof is public.<br/>The losing bid amounts don’t have to be.</p></div><div className="verify-mark"><SealMark size={108}/></div></div><section className="verify-search"><form onSubmit={inspect}><label htmlFor="auction-id">Auction ID</label><div className="search-row"><input id="auction-id" value={id} onChange={e=>setId(e.target.value)} inputMode="numeric" placeholder="e.g. 1" required/><button className="button button-primary" disabled={busy}>{busy?"Reading registry…":"Inspect evidence"}<Arrow/></button></div></form>{error&&<ErrorNotice message={error}/>}</section>
{auction&&<section className="evidence-panel"><div className="section-heading"><div><span className="eyebrow muted">AUCTION {auction.id}</span><h2>{auction.title}</h2></div><Phase phase={auction.phase}/></div><dl className="rules-grid"><div><dt>Registered bids</dt><dd>{auction.bidCount} / 16</dd></div><div><dt>Registry snapshot</dt><dd>Block {auction.snapshotBlock}</dd></div><div><dt>Rules hash</dt><dd className="mono">{short(auction.rulesHash,10)}</dd></div><div><dt>Reported result</dt><dd>{auction.result?.sale?`${zec(auction.result.price)} ZEC`:auction.result?"No sale":"Not finalized"}</dd></div></dl><p className="notice">This page displays the service’s finalized registry snapshot. For verification independent of this website, check the canonical contract and proof using the command below.</p>{proof?<button className="button button-outline" onClick={()=>downloadJson(`auction-${id}-proof.json`,proof)}>Download proof bundle ↓</button>:<p className="muted">No public proof bundle is available yet. A pending or blocked auction is not a verified result.</p>}</section>}
<div className="verification-grid"><section><span className="eyebrow muted">WHAT THE PROOF CHECKS</span><h2>Fairness you<br/>can <em>inspect.</em></h2><ol className="verification-checks"><li>Every active registered commitment opens to a valid bid.</li><li>The highest eligible amount wins under the fixed reserve.</li><li>Equal highest bids use the earliest registration index.</li><li>The winner’s identity and first-price amount match that bid.</li><li>No registered bid is silently omitted.</li></ol></section><section className="command-panel"><span className="mono">VERIFY OUTSIDE THIS WEBSITE</span><h3>Bring your own RPC.</h3><p>From the repository, use a trusted Base Sepolia RPC and the independently checked registry address. The verifier must check canonical chain state, not just a downloaded list.</p><pre><code>{`VERIFY_RPC_URL=https://your-trusted-rpc \\\n npm run verify -- \\\n  reviewed-deployment.json \\\n  proof-bundle.json ${id||"<auction-id>"}`}</code></pre><p className="tiny">Use an independently reviewed deployment manifest. The command checks chain identity, registry and verifier code hashes, canonical state, and the proof. See README for setup; do not blindly trust a manifest from this website.</p><Link href="/#how-it-works" className="text-link">Understand the full flow <Arrow diagonal/></Link></section></div><div className="trust-note"><span className="mono">WHAT A PROOF DOESN’T PROMISE</span><p>It does not prove bidders are different people, that the winner will pay, or that the seller will deliver. It also does not hide opened bids from the evaluator or verify a Zcash payment.</p></div></main>;}

export default function VerifyPage(){return <Suspense fallback={<main id="main" className="page-content">Loading verification…</main>}><VerifyContent/></Suspense>;}
